FROM nginxinc/nginx-unprivileged:1.28-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY index.html app.js data-management.js stocks.js calculator.js cashflow.js activity.js style.css data-management.css stocks.css calculator.css activity.css /usr/share/nginx/html/
