/* Stock search, market data, and chart rendering. */
let stockState={query:'',exchange:'',results:[],searching:false,error:'',selected:'',range:'1y',overview:null,candles:null,financials:null,loading:false,request:0,highlight:-1,suggestionsOpen:false,candleIndex:null};
let stockSearchTimer=null,stockSearchController=null,stockLoadController=null;
function stockSearchPanel(){return `<div class="panel stock-search"><div class="stock-search-row"><label>Search by ticker or company<input id="stock-search-input" role="combobox" value="${esc(stockState.query)}" placeholder="AAPL, VWRA, DBS…" autocomplete="off" aria-autocomplete="list" aria-controls="stock-search-results" aria-expanded="${stockState.suggestionsOpen}" ${stockState.highlight>=0?`aria-activedescendant="stock-option-${stockState.highlight}"`:''}></label><label>Exchange<select id="stock-exchange"><option value="">All exchanges</option>${['NASDAQ','NYSE','LSE','SGX'].map(x=>`<option ${stockState.exchange===x?'selected':''}>${x}</option>`).join('')}</select></label><button type="button" data-action="stock-search">Search</button></div><div id="stock-search-results" role="listbox">${stockSearchResults()}</div></div>`;}
function stockSearchResults(){
  if(!stockState.suggestionsOpen)return '';
  if(stockState.searching)return `<div class="stock-search-status">Searching…</div>`;
  if(stockState.error)return `<div class="stock-search-status error">${esc(stockState.error)} <button class="text-button" data-action="stock-search">Retry</button></div>`;
  if(stockState.query&&stockState.results.length===0)return `<div class="stock-search-status">No matching securities found.</div>`;
  return stockState.results.map((item,index)=>`<button type="button" id="stock-option-${index}" role="option" aria-selected="${index===stockState.highlight}" class="stock-option ${index===stockState.highlight?'active':''}" data-action="stock-option" data-index="${index}"><span><strong>${esc(item.symbol)}</strong><small>${esc(item.name)}</small></span><span>${badge(item.exchange)}<small>${esc(item.currency)}</small></span></button>`).join('');
}
function renderStockSearch(){const results=$('#stock-search-results'),input=$('#stock-search-input');if(results)results.innerHTML=stockSearchResults();if(input){input.setAttribute('aria-expanded',String(stockState.suggestionsOpen));if(stockState.highlight>=0)input.setAttribute('aria-activedescendant',`stock-option-${stockState.highlight}`);else input.removeAttribute('aria-activedescendant');}}
function chooseStockResult(index){const item=stockState.results[index];if(!item)return;stockState.suggestionsOpen=false;stockState.highlight=-1;location.hash=`stocks/${encodeURIComponent(item.security_id)}`;}
function stocksPage(id){
  const selected=id?decodeURIComponent(id):'';
  if(selected&&selected!==stockState.selected)queueMicrotask(()=>loadStock(selected));
  return `${stockSearchPanel()}${selected?stockDetail(selected):`<div class="panel stock-empty">${empty('Find a stock or ETF','Search by ticker or company name. Every result includes its exchange so duplicate tickers remain distinct.')}</div>`}`;
}
function stockDetail(securityId){
  if(stockState.loading||stockState.selected!==securityId)return stockSkeleton();
  if(stockState.error)return `<div class="panel">${empty('Market data is unavailable',`${esc(stockState.error)} <button class="small-button" data-action="stock-retry">Retry</button>`)}</div>`;
  const overview=stockState.overview,price=overview?.latest_price,security=overview?.security;if(!overview||!price||!security)return stockSkeleton();
  const candles=stockState.candles?.candles||[],previous=candles.at(-2),fallbackChange=previous?Number(price.close)-Number(previous.close):null,change=price.change==null?fallbackChange:Number(price.change),pct=price.change_percent==null?(previous&&Number(previous.close)!==0?change/Number(previous.close)*100:null):Number(price.change_percent),stale=overview.cache?.stale||stockState.candles?.cache?.stale||stockState.financials?.cache?.stale;
  return `${stale?`<div class="notice"><strong>Showing stale cached market data</strong><p>Provider refresh is unavailable. Values retain their original as-of dates.</p><button class="small-button" data-action="stock-retry">Retry</button></div>`:''}<div class="panel stock-head"><div><p class="eyebrow">${esc(security.exchange)} · ${esc(security.currency)}</p><h2>${esc(security.name)}</h2><p>${esc(security.symbol)} · Completed session ${esc(price.session_date)}</p></div><div class="stock-price"><strong>${esc(price.currency)} ${fmt(price.close)}</strong><span class="${change==null?'':change>=0?'positive':'negative'}">${change==null?'-':`${change>=0?'+':''}${fmt(change)} (${pct>=0?'+':''}${fmt(pct)}%)`}</span><small>${stale?'Stale cache · ':''}As of ${esc(price.session_date)} · ${esc(price.market_status)}</small></div></div><div class="panel"><div class="panel-head"><h2>Daily price</h2><div class="stock-ranges">${['1y','3y','5y','max'].map(range=>`<button data-action="stock-range" data-value="${range}" class="${stockState.range===range?'active':''}">${range==='max'?'Max':range.toUpperCase()}</button>`).join('')}</div></div>${candlestickChart(stockState.candles)}<details><summary>Accessible daily-price table</summary>${candleTable(candles)}</details></div>${fundamentalsTable(stockState.financials)}`;
}
function stockSkeleton(){return `<div class="stock-skeleton"><div></div><div></div><div></div></div>`;}
function candlestickChart(payload){
  const rows=payload?.candles||[];if(!rows.length)return empty('No completed-session prices','Daily OHLCV data is unavailable for this range.');
  const w=900,h=330,p={l:72,r:18,t:20,b:34},lows=rows.map(r=>Number(r.low)),highs=rows.map(r=>Number(r.high)),min=Math.min(...lows),max=Math.max(...highs),slot=(w-p.l-p.r)/rows.length,body=Math.max(.8,Math.min(7,slot*.64)),x=i=>p.l+(i+.5)*slot,y=v=>p.t+(max-v)/(max-min||1)*(h-p.t-p.b);
  const marks=rows.map((r,i)=>{const open=Number(r.open),close=Number(r.close),up=close>=open,top=y(Math.max(open,close)),height=Math.max(1,Math.abs(y(open)-y(close)));return `<g class="candle ${up?'up':'down'}"><line x1="${x(i)}" x2="${x(i)}" y1="${y(Number(r.high))}" y2="${y(Number(r.low))}"/><rect x="${x(i)-body/2}" y="${top}" width="${body}" height="${height}"/></g>`}).join('');
  return `<div class="candle-chart" data-security="${esc(payload.security_id)}" data-currency="${esc(payload.currency)}" tabindex="0" aria-label="Interactive daily candlestick chart. Use Left and Right arrows to inspect completed sessions." aria-describedby="candle-announcement"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Daily candlestick chart for ${esc(payload.security_id)}, ${esc(rows[0].date)} through ${esc(rows.at(-1).date)}, in ${esc(payload.currency)}"><line class="chart-axis" x1="${p.l}" x2="${p.l}" y1="${p.t}" y2="${h-p.b}"/>${marks}<text x="4" y="${p.t+5}">${esc(payload.currency)} ${fmt(max)}</text><text x="4" y="${h-p.b}">${esc(payload.currency)} ${fmt(min)}</text><text x="${p.l}" y="${h-8}">${esc(rows[0].date)}</text><text text-anchor="end" x="${w-p.r}" y="${h-8}">${esc(rows.at(-1).date)}</text><line class="candle-cursor" hidden y1="${p.t}" y2="${h-p.b}"/><circle class="candle-close-point" hidden r="5"/><rect class="candle-hit" data-action="stock-candle-hover" x="${p.l}" y="${p.t}" width="${w-p.l-p.r}" height="${h-p.t-p.b}"/></svg><div class="candle-tooltip" hidden></div><span id="candle-announcement" class="sr-only" aria-live="polite"></span></div><p class="section-note">Completed daily sessions only · Move, tap, drag, or use arrow keys to inspect · As of ${esc(payload.as_of)}</p>`;
}
function nearestCandleIndex(clientX,left,width,count){if(count<=1)return 0;const viewX=(clientX-left)/width*900,ratio=Math.max(0,Math.min(1,(viewX-72)/(900-72-18)));return Math.max(0,Math.min(count-1,Math.round(ratio*(count-1))));}
function clampTooltipLeft(value,width,half=92){return Math.max(half,Math.min(Math.max(half,width-half),value));}
function nextCandleIndex(current,key,count){if(!count)return null;const fallback=key==='ArrowLeft'?count: -1,index=current==null?fallback:Number(current);return Math.max(0,Math.min(count-1,index+(key==='ArrowRight'?1:-1)));}
function selectCandle(root,index,pinned=false){
  const rows=stockState.candles?.candles||[];if(!root||!rows.length)return;index=Math.max(0,Math.min(rows.length-1,index));const row=rows[index],svg=root.querySelector('svg'),slot=(900-72-18)/rows.length,x=72+(index+.5)*slot,lows=rows.map(r=>Number(r.low)),highs=rows.map(r=>Number(r.high)),min=Math.min(...lows),max=Math.max(...highs),y=20+(max-Number(row.close))/(max-min||1)*(330-20-34),cursor=svg.querySelector('.candle-cursor'),point=svg.querySelector('.candle-close-point'),tip=root.querySelector('.candle-tooltip'),announcement=root.querySelector('#candle-announcement'),currency=root.dataset.currency||'';
  cursor.hidden=false;point.hidden=false;cursor.setAttribute('x1',x);cursor.setAttribute('x2',x);point.setAttribute('cx',x);point.setAttribute('cy',y);tip.hidden=false;tip.style.left=`${clampTooltipLeft(x/900*svg.clientWidth+(svg.offsetLeft||0),root.clientWidth)}px`;tip.innerHTML=`<strong class="candle-tooltip-date">${esc(row.date)}</strong><span class="candle-tooltip-close"><small>Close</small><b>${esc(currency)} ${fmt(row.close)}</b></span><span class="candle-tooltip-values"><small><i>Open</i><b>${fmt(row.open)}</b></small><small><i>High</i><b>${fmt(row.high)}</b></small><small><i>Low</i><b>${fmt(row.low)}</b></small><small class="volume"><i>Volume</i><b>${Number(row.volume??0).toLocaleString('en-SG')}</b></small></span>`;announcement.textContent=`${row.date}. Close ${currency} ${fmt(row.close)}. Open ${fmt(row.open)}, high ${fmt(row.high)}, low ${fmt(row.low)}, volume ${Number(row.volume??0).toLocaleString('en-SG')}.`;root.dataset.pinned=String(pinned);root.dataset.candleIndex=String(index);stockState.candleIndex=index;
}
function clearCandle(root){root.querySelector('.candle-cursor')?.setAttribute('hidden','');root.querySelector('.candle-close-point')?.setAttribute('hidden','');const tip=root.querySelector('.candle-tooltip');if(tip)tip.hidden=true;}
function candleFromPointer(event,pinned=false){const root=event.target.closest('.candle-chart'),svg=root?.querySelector('svg'),rows=stockState.candles?.candles||[];if(!root||!svg||!rows.length)return;const box=svg.getBoundingClientRect();selectCandle(root,nearestCandleIndex(event.clientX,box.left,box.width,rows.length),pinned);}
function candleTable(rows){return `<div class="schedule-scroll table-wrap"><table><thead><tr><th>Date</th><th class="num">Open</th><th class="num">High</th><th class="num">Low</th><th class="num">Close</th><th class="num">Volume</th></tr></thead><tbody>${rows.slice().reverse().map(r=>`<tr><td>${esc(r.date)}</td><td class="num">${fmt(r.open)}</td><td class="num">${fmt(r.high)}</td><td class="num">${fmt(r.low)}</td><td class="num">${fmt(r.close)}</td><td class="num">${Number(r.volume??0).toLocaleString('en-SG')}</td></tr>`).join('')}</tbody></table></div>`;}
function financialValue(value,currency){return value==null?'-':`${esc(currency)} ${Number(value).toLocaleString('en-SG',{maximumFractionDigits:0})}`;}
function fundamentalsTable(payload){
  const years=payload?.fiscal_years||[],currency=payload?.currency||'';if(!years.length)return `<div class="panel">${empty('No fundamentals available','The provider did not return annual financial statements for this security.')}</div>`;
  const showEbita=years.some(y=>y.ebita!=null);return `<div class="panel"><div class="panel-head"><h2>Five-year fundamentals</h2><small>${esc(currency)} · REPORTED VALUES</small></div>${payload.coverage&&!payload.coverage.complete?`<p class="section-note">${esc(payload.coverage.returned_years)} of ${esc(payload.coverage.requested_years)} requested fiscal years are available.</p>`:''}<div class="table-wrap"><table><thead><tr><th>Fiscal year</th><th>Period end</th><th class="num">Revenue</th><th class="num">Free cash flow</th><th class="num">Profit after tax</th><th class="num">EBITDA</th>${showEbita?'<th class="num">EBITA</th>':''}</tr></thead><tbody>${years.map(y=>`<tr><td>${esc(y.fiscal_year)}</td><td>${esc(y.period_end)}</td><td class="num">${financialValue(y.revenue,currency)}</td><td class="num">${financialValue(y.free_cash_flow,currency)}</td><td class="num">${financialValue(y.profit_after_tax,currency)}</td><td class="num">${financialValue(y.ebitda,currency)}</td>${showEbita?`<td class="num">${financialValue(y.ebita,currency)}</td>`:''}</tr>`).join('')}</tbody></table></div></div>`;
}
async function searchStocks(){
  const input=$('#stock-search-input'),exchange=$('#stock-exchange');if(input){stockState.query=input.value.trim();stockState.exchange=exchange.value;}stockState.suggestionsOpen=true;stockState.highlight=-1;if(!stockState.query){stockState.results=[];stockState.error='';stockState.searching=false;renderStockSearch();return;}
  stockSearchController?.abort();stockSearchController=new AbortController();const request=++stockState.request;stockState.searching=true;stockState.error='';renderStockSearch();
  try{const params=new URLSearchParams({q:stockState.query});if(stockState.exchange)params.set('exchange',stockState.exchange);const result=await api('/stocks/search?'+params,{signal:stockSearchController.signal});if(request!==stockState.request)return;stockState.results=result.results||[];}
  catch(error){if(error.name!=='AbortError'&&request===stockState.request)stockState.error=error.message;}finally{if(request===stockState.request){stockState.searching=false;renderStockSearch();}}
}
async function loadStock(securityId,force=false){
  if(!force&&stockState.selected===securityId&&stockState.overview)return;stockLoadController?.abort();stockLoadController=new AbortController();const request=++stockState.request;stockState={...stockState,selected:securityId,loading:true,error:'',overview:null,candles:null,financials:null,request,candleIndex:null};render();const encoded=encodeURIComponent(securityId);
  try{const [overview,candles,financials]=await Promise.all([api(`/stocks/${encoded}/overview`,{signal:stockLoadController.signal}),api(`/stocks/${encoded}/candles?range=${stockState.range}&interval=1d`,{signal:stockLoadController.signal}),api(`/stocks/${encoded}/financials?years=5`,{signal:stockLoadController.signal})]);if(request!==stockState.request)return;Object.assign(stockState,{overview,candles,financials,loading:false});}
  catch(error){if(error.name!=='AbortError'&&request===stockState.request)Object.assign(stockState,{error:error.message,loading:false});}finally{if(request===stockState.request)render();}
}
